### ISSUE TITLE
Publish Python 3.6 wheel 

### ISSUE THREAD

**Issue by whs** [hynek/argon2_cffi#24]
Please upload a prebuilt wheel for Python 3.6 to PyPi.

**Comment by ofek** [comment]
+1

**Comment by hynek** [comment]
Just to be clear: I hear y’all and would *love* to give you your delicious wheels.

Sadly it’s a bit problematic to build them since *two* different CIs are involved (AppVeyor for Windows & Jenkins for macOS) and I’d have to make them build older revisions.  I’m sure it’s possible but I just don’t have the time to figure it out – sorry.

My hope is that upstream will tag a new version sometime soon so I can release a new version (which is fully automated).

**Comment by hynek** [comment]
Plot twist: I have just uploaded (hopefully) all relevant 3.6 wheels.  All thanks belongs to @reaperhulk tho.
