### ISSUE TITLE
Fix verify to return false instead of raising error

### ISSUE THREAD

**Issue by ranisalt** [hynek/argon2_cffi#8]
Hey!

On [your article](https://hynek.me/articles/storing-passwords/) you said:

> In case you wonder why verify() raises an exception instead of just returning False: the Argon2 library has no concept of a “wrong password” error. Therefore an exception with the full error is raised so you can inspect what went wrong if needed. Also IMHO a wrong password should raise an exception such that it can’t pass unnoticed by accident.

That's not true anymore since [b07d7b6](https://github.com/P-H-C/phc-winner-argon2/commit/b07d7b68c9615021151db6077e732956f5984b48) :smile:

**Comment by hynek** [comment]
Yeah and I *may* do the API differently if I designed it today.  **But** can you imagine what would happen if:

1. I changed the API from raising an exception to returning False? (free entry on *all* existing installations*
2. Had one API that raises and error and one API the returns False? (people would keep mixing it up leading to )

TBH I cannot find a responsible way to make you happy without introducing a high probability of security vulnerabilities due to changing/inconsistent APIs.

**Comment by ranisalt** [comment]
I have an idea. You can (and probably should) keep the exceptions BUT you could raise a different exception on verification failure. Users may proceed differently on mismatch or other failuer type.

**Comment by hynek** [comment]
Yeah I planned a VerificationError sub-class WrongSecretError or whatever that gets caught along as before but allows for finer grained handling.

**Comment by hynek** [comment]
Fixed in e7aaa80.
